package com.mor.test;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.tree.DefaultElement;
import org.junit.BeforeClass;

public abstract class XMLConsumingTestCase extends PropertiesConsumingTestCase {

    @BeforeClass
    public static void initialise() {

        setupTestSettings();

    }

    public static Document getDefautDocument() {
        try {
            return DocumentHelper.parseText(
                    "<root></root>"
                    );
        }
        catch (DocumentException ex) {
            Logger.getLogger(XMLConsumingTestCase.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public static Document getBlogDocument() {
        String docText = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->\n"
                + "\n"
                + "<Blog xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"blog.xsd\">\n"
                + "    <Entry date=\"2004-09-09\" ID=\"ID_152369776\" categoryID=\"ID_1222333\" allowComments=\"false\" >\n"
                + "       \n"
                + "        <Text>\n"
                + "            test entry !\n"
                + "        </Text>\n"
                + "        <Resume>\n"
                + "            feed\n"
                + "        </Resume>\n"
                + "        <Comment ID=\"ID_1476476016\" date=\"Mon Nov 23 00:00:00 EST 2009\" entryID=\"ID_152369776\" author=\"Mike\" webPage=\"no page\">\n"
                + "            <CommentText>Hi HI</CommentText>\n"
                + "        </Comment>\n"
                + "    </Entry>\n"
                + "    <Category name=\"test\" ID=\"ID_1222333\"/>\n"
                + "\n"
                + "\n"
                + "    <Category ID=\"ID_320524799\" name=\"added\" description=\"\"/>\n"
                + "\n"
                + "    <Category ID=\"ID_-492027613\" name=\"remove\" description=\"\"/>\n"
                + "\n"
                + "</Blog>";
        try {
            return DocumentHelper.parseText(
                    docText
                    );
        }
        catch (DocumentException ex) {
            Logger.getLogger(XMLConsumingTestCase.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

}
